server:
  host: "0.0.0.0"
  port: 8080
  api_key: "api-key-test"

storage:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "bucket-1"
  use_ssl: false
  region: "us-east-1"

upload:
  allowed_extensions:
    - ".tar"
    - ".deb"
    - ".rpm"
    - ".bin"
    - ".zip"
  max_file_size_bytes: 10000000 # 10MB
  max_batch_files: 10

naming:
  prefix: "artifacts"
